[package]
name = "talkscript"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
simple-ternary = "0.3.0"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "talkscript_benchmark"
harness = false
